### ISSUE TITLE
how does this compare with linc_glfw ?

### ISSUE THREAD

**Issue by nanjizal** [ibilon/hxglfw#1]
how does this compare with linc_glfw ?
Have been experimenting without visual success but some compile.
The infinite while loop is not ideal.
https://github.com/TrilateralX/TrilateralGluonChange/blob/master/src/trilateralGluonChange/AppGL.hx#L30
https://github.com/TrilateralX/TrilateralGluonSVG/blob/master/TrilateralGluonSVG.hx
( There is webgl and lime version on TrilateralX for comparisom. )

**Comment by ibilon** [comment]
The main difference is that hxglfw wraps glfw into an oop api, hiding the externs/pointers behind a more haxe friendly api. This is quite subjective whether you prefer the raw c api or not.

It's also a work in progress, it currently covers monitors/windows, and I'll soon add inputs. I don't currently have plans to add opengl context support since I won't be using it, but if some people would want that I could try.

I don't think the while loop is strictly necessary, as long as the events are polled frequently enough for the window to be responsive it should work, so you should be able to make your own main loop (in either lib).

**Comment by nanjizal** [comment]
ibilon for reference gluon with linc_sdl can be found here modified from code George provided, I am still working on integration with my lib, and reporting bugs to George, but perhaps interesting and may give insight on setup of hxglfw with gluon.
https://github.com/nanjizal/glueTest/
